services:
  db:
    image: postgres:16.9
    container_name: morbis_db
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - morbis-net

  backend:
    build: ./back
    container_name: morbis_backend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./back:/app
    env_file:
      - ./back/.env
    networks:
      - morbis-net

  frontend:
    build:
      context: .
      dockerfile: front/Dockerfile
    container_name: morbis_frontend
    restart: always
    ports:
      - "8050:8050"
    depends_on:
      - backend
    volumes:
      - ./front:/app
      - ./data:/app/data
    networks:
      - morbis-net

networks:
  morbis-net:

volumes:
  pgdata:
